version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3900:3900"
    environment:
      - DATABASE=mongodb+srv://robincyril24:Robin1993@cluster0.rebkxr7.mongodb.net/test?retryWrites=true&w=majority
